newrelic/newrelic-lambda-layers

extension/publish-layer.sh
nodejs/publish-layers.sh
python/publish-layers.sh

Extension 1.0.2

---

extension/publish-layer.sh
nodejs/publish-layers.sh
python/publish-layers.sh

The extra decimal in the URL reflects a unit testing change.

Extension 1.2.1 URL

---

create-buckets.sh
extension/publish-layer.sh
java/publish-layers.sh
nodejs/publish-layers.sh
python/publish-layers.sh

(feat): Publish to eu-north-1

---

extension/publish-layer.sh
java/publish-layers.sh
nodejs/publish-layers.sh
python/publish-layers.sh

Supporting Py3.9 and supporting logs api platform.start record as string

(feat): Extension release 2.0.3

---

extension/publish-layer.sh

This is just the vanilla extension currently, the runtime specific layers are more involved.

Add ARM64 Lambda Extension Publishing

---

.circleci/config.yml
Makefile
dockerfiles/Dockerfile.java11
dockerfiles/Dockerfile.java8al2
java/build.gradle
java/publish-layers.sh

This also Dockerizes the builds.

Add ARM64 Build For Java Runtimes

---

extension/publish-layer.sh
java/publish-layers.sh
nodejs/publish-layers.sh
python/publish-layers.sh

feat: Adding previously-unsupported regions

---

java/build.gradle
java/publish-layers.sh

Fix bash function syntax

---

extension/publish-layer.sh
java/publish-layers.sh
libBuild.sh
nodejs/publish-layers.sh
python/publish-layers.sh

Rewrite the build scripts to factor out common behavior into a shared library.

DRY build refactor

---

libBuild.sh

A couple small build issues.
The `which` issue didn't show up locally, because the output is naturally empty, and I didn't catch the stray curly in my visual inspection of the test output.

fixes to the build process

---

nodejs/index.js

feat: Added support for handler paths with hidden directories

---

.circleci/config.yml
nodejs/.eslintrc
nodejs/index.js
nodejs/package-lock.json
nodejs/package.json
nodejs/test/fixtures/.hidden/.directory/.handler.js
nodejs/test/fixtures/handler.js
nodejs/test/layer.tap.js

* Added test to Node wrapper
* Added tests to CircleCI
* Removed IOpipe adapter

Added Node tests, removed legacy adapter

---

.circleci/config.yml

NR-55595 CIrcleCI runs commands from project root. This cds for running the tests. 

fix: Added directory change to test command

---

nodejs/package.json

fix: Added install before tests

---

nodejs/package.json

fix: No longer removing agent log; it's not present on first run

---

.circleci/config.yml
nodejs/package.json

Set up CircleCI-friendly test commands as an alternative to local testing

fix: Set up CircleCI-friendly tests

---

.circleci/config.yml
README.md
nodejs/.c8rc.json
nodejs/package-lock.json
nodejs/package.json

* Updated tests to use c8
* Added codecov upload to CI build
* https://app.codecov.io/gh/newrelic/newrelic-lambda-layers/tree/NR-60811-codecov

NR-60811 wire up c8 and codecov for coverage collection

---

.circleci/config.yml
Makefile
dockerfiles/Dockerfile.nodejs18x
libBuild.sh
nodejs/publish-layers.sh

feat: Added support for Node 18, from a PR submitted by @Engerim on https://github.com/newrelic/newrelic-lambda-layers/pull/118
This branch is just to fix merge conflicts.

Add support for nodejs18

---

nodejs/index.js
nodejs/package-lock.json
nodejs/package.json

fix: Removed check for Node 18 for import retry (closes NEWRELIC-5925)
chore: Audit-fixed dependencies
chore: version bump

Removed version check for import

---

python/newrelic_lambda_wrapper.py

This fixes #90 by switching the handler import code to use `importlib`, instead of the now deprecated `imp`. This has the side bonus of simplifying the code.
This matches the current `awslambdaric` bootstrapping code more closely (<https://github.com/aws/aws-lambda-python-runtime-interface-client/blob/97dee252434edc56be4cafd54a9af1e7fa041eaf/awslambdaric/bootstrap.py#L33-L39>)  following the changes in <https://github.com/aws/aws-lambda-python-runtime-interface-client/commit/620b14824600db3c32ba8e234e3175dbece8b8b5>.
---
I've tested this against a lambda deployed as a PEX (https://github.com/pantsbuild/pex).:
- Background: These are a self-contained executable (includes dependencies and so on) that does various magic to set up those dependencies when importing via a `__pex__` …

Use importlib to import Python handlers

---

java/build.gradle

Jira: https://issues.newrelic.com/browse/NR-112739

Update fasterxml dependency to address CVE-2022-42003

---

libBuild.sh

Fixes https://github.com/newrelic/newrelic-lambda-layers/issues/161

Update libBuild.sh extension version to latest

---

nodejs/package-lock.json
nodejs/package.json

chore: Updated devDependencies in Node tests

---

README.md

Added instructions for manual ESM wrapping, and added note on dynamic import performance

chore: Added documentation on manual wrapping for ESM

---

Makefile

Added Node-20-specific commands to the Makefile.

fix: Added Node 20 blocks to Makefile for ci publishing

---

libBuild.sh

Update libBuild.sh extension version

---

.circleci/config.yml
libBuild.sh
python/publish-layers.sh

This PR adds config/ workflows for building & deploying Python 3.12 lambda layers.

Add Python 3.12 layers.

---

libBuild.sh

Update libBuild.sh for latest lambda extension release

---

.github/workflows/java_snyk_scan.yml
.github/workflows/repolinter.yml

[Issue #1517](https://github.com/newrelic/newrelic-java-agent/issues/1517)

Migrate Repolinter and Snyk Workflows to use Node 20

---

ruby/publish-layers.sh

By matching the granularity of the Python script, consumers of the scripts can build without publishing and also easily get at the filenames of the built layer .zip files.
see: https://github.com/newrelic/newrelic-ruby-agent/issues/2638

update ruby/publish-layers.sh to be more granular

---

libBuild.sh

Update extension version to v2.3.12 for publishing the layers with latest extension

update extension version 

---

README.md

update readme publish-layer script for the [github issue](https://github.com/newrelic/newrelic-lambda-layers/issues/71)

update readme publish-layer script

---

ruby/publish-layers.sh

- Test docker hub release for Ruby images to docker hub

test docker hub

---

ruby/publish-layers.sh

Reverts newrelic/newrelic-lambda-layers#260

Revert "test docker hub"

---

python/newrelic_lambda/__init__.py
python/newrelic_lambda/agent_protocol.py
python/newrelic_lambda/event-sources.json
python/newrelic_lambda/lambda_handler.py
python/publish-layers.sh

* Add code from old `newrelic-lambda` package on PyPi directly into lambda.
* Update parsing logic for lambdas to handle new locations for http method and path.

Add python's newrelic_lambda package directly to layers

---

libBuild.sh

Update extension image repo to newrelic-lambda-layers-lambdaextension as in production we have https://gallery.ecr.aws/x6n7b2o2/newrelic-lambda-layers-lambdaextension

update image repo name

---

java/build.gradle

Upgrade `java-aws-lambda-2.1.1` dependency to `java-aws-lambda-2.2.0`

Upgrade java-aws-lambda Dependency

---

.github/workflows/publish-dotnet.yml
.github/workflows/publish-extension.yml
.github/workflows/publish-java.yml
.github/workflows/publish-node.yml
.github/workflows/publish-python.yml
.github/workflows/publish-ruby.yml
libBuild.sh

- Resolves issue raised [here](https://github.com/newrelic/newrelic-lambda-layers/issues/274) regarding running a container on Apple Silicon with layers `newrelic-lambda-layers-nodejs:20-arm64` is resulting in errors.
- Since github actions does not support cross-platform docker build, we will use emulator - [qemu](https://github.com/docker/setup-qemu-action)
- Modify github workflow for all runtime to add qemu before the docker build step.

resolve docker ecr arm images issue

---

.github/workflows/dependency-submission.yml

Update Dependency Submission Workflow

---

.github/workflows/nodejs.yml
Makefile
nodejs/publish-layers.sh

- rectify workflow to Nodejs22 layer and ecr image release

Rectify workflow for Nodejs22 layer release

---

.github/workflows/publish-node.yml

- Updating codecov version which helps in resolving `node.js` workflow failed.

chore: updating codecov version in nodejs workflow

---

.github/workflows/publish-node.yml

Reverts newrelic/newrelic-lambda-layers#307

Revert "chore: updating codecov version in nodejs workflow"

---

libBuild.sh

extension v2.3.17 release

---

python/newrelic_lambda_wrapper.py

- `NEW_RELIC_PACKAGE_REPORTING_ENABLED` made it by default false. Since its increasing total duration as per our analysis.
- Created layer for the change and tested the changes.
Resolves #195

chore: Disabling NEW_RELIC_PACKAGE_REPORTING_ENABLED by default

---

java/build.gradle

Related to https://github.com/newrelic/newrelic-lambda-tracer-java/issues/46

Update to newrelic-java-lambda:2.2.4

---

.github/workflows/ruby.yml
ruby/test/lambda_wrapper_integration_test.rb
ruby/test/lambda_wrapper_parsing_test.rb
ruby/test/support/package.json

Rectify Ruby workflow

---

libBuild.sh

update extension for release

---

libBuild.sh

Reverts newrelic/newrelic-lambda-layers#344

Revert "update extension for release"

---

dotnet/publish-layers.sh
libBuild.sh

add agent version to layer description

add agent version to layer description

---

libBuild.sh

This PR updates extension version from `2.3.19` to `2.3.20`

chore: update extension version to 2.3.20

---

libBuild.sh

release extension v2.3.21

---

dotnet/publish-layers.sh
extension/publish-layer.sh
java/publish-layers.sh
libBuild.sh
nodejs/publish-layers.sh
python/publish-layers.sh
ruby/publish-layers.sh

Ticket: [NR-447337](https://new-relic.atlassian.net/browse/NR-447337)
[NR-447337]: https://new-relic.atlassian.net/browse/NR-447337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: updated region variable

---

libBuild.sh
ruby/publish-layers.sh

- add ruby version in Layer description

add ruby version in Layer description

---

.github/workflows/publish-node.yml
Makefile
dockerfiles/Dockerfile.nodejs16

add nodejs16 workflow

---

libBuild.sh

rename layer for nodejs

---

libBuild.sh

Reverts newrelic/newrelic-lambda-layers#396

Revert "update layer description for nodejs16"
