newrelic/newrelic-lambda-layers

python/newrelic_lambda_wrapper.py
To make it easier to debug why a module failed to import, include the ImportError message.
=> Output Import Error Message

.circleci/config.yml, python/publish-layers.sh
AWS now supports Python 3.9 as a Lambda runtime, and the NR Python agent also supports 3.9. This adds layer support.
=> (feat): Build layer for Python 3.9

.circleci/config.yml, README.md, java/publish-layers.sh, nodejs/publish-layers.sh, python/publish-layers.sh
Node 10 was officially out of stage 2 support on September 17. Python 2.7 is out of stage 2 support September 30.
=> fix: Remove deprecated runtimes

java/src/main/java/com/newrelic/java/JavaClassLoader.java
Wrapping java functions when HandlerBase comes from a different package than the Handler class.
This has been smoke-tested with a user-supplied function and a custom layer. 
=> feat: HandlerBase and Handler in different packages

nodejs/index.js, nodejs/package-lock.json, nodejs/package.json, nodejs/publish-layers.sh
The Node.js agent team published semver major bumps last summer to support Node 16.  This Pr upgrades the `newrelic` package.  I also uninstalled the `@newrelic/aws-sdk` as it is bundled with our agent
=> upgraded newrelic to latest

.circleci/config.yml, Makefile, dockerfiles/Dockerfile.nodejs12x, dockerfiles/Dockerfile.nodejs14x, nodejs/publish-layers.sh
All layers should be built and published in their own containers. This gets the ball rolling.
=> Dockerize Node Layer Builds

java/build.gradle, java/publish-layers.sh
Reworked the gradle build to include the all the Java deps in the zip. 
Gradle now produces the distribution zip, rather than the shell script
=> Fix build to include dependencies

java/build.gradle, java/src/main/java/com/newrelic/java/HandlerWrapper.java, java/src/main/java/com/newrelic/java/JavaClassLoader.java, java/src/test/java/com/newrelic/java/BiFunctionHandlerWithObjectInput.java, java/src/test/java/com/newrelic/java/BiFunctionHandlerWithStringInput.java, java/src/test/java/com/newrelic/java/FunctionHandlerWithObjectInput.java, java/src/test/java/com/newrelic/java/FunctionHandlerWithStringInput.java, java/src/test/java/com/newrelic/java/HandlerWrapperTest.java, java/src/test/java/com/newrelic/java/Input.java, java/src/test/java/com/newrelic/java/JavaClassLoaderTest.java, java/src/test/java/com/newrelic/java/RequestHandlerWithObjectInput.java, java/src/test/java/com/newrelic/java/RequestHandlerWithStringInput.java, java/src/test/java/com/newrelic/java/TestStreamingRequestHandler.java
The current Java implementation is very restrictive in terms of the method signatures. At least the following use cases are not covered
1. the handler method does not accept `Context`
2. the handler method does accept `Context` as bounded parameter
3. the input type is not `Object` or generic type parameter
Some design flaws has been also fixed:
1. The extensive usage of static fields
2. Dual functionality of `JavaClassPath` object
3. The naming of `JavaClassPath` class was not descriptive
Tests were added to cover the most common use cases.
Fixes #50.
=> Support any Java handler

java/build.gradle
This fixes the missing tracer dependencies in the Java layer without needing to add them explicitly.
=> fix: Including tracer deps by building with runtimeClasspath

dockerfiles/Dockerfile.java11, dockerfiles/Dockerfile.java8al2, dockerfiles/Dockerfile.nodejs12x, dockerfiles/Dockerfile.nodejs14x
Docker build was flattening the dir structure, which broke when I started referring to files in the parent dir.
=> Adjust dockerfile build to preserve dir structure

dockerfiles/Dockerfile.java11, dockerfiles/Dockerfile.java8al2, dockerfiles/Dockerfile.nodejs12x, dockerfiles/Dockerfile.nodejs14x
For some reason, we've chosen to create a new user within the container to run the build, but the docker `COPY` defaults to root ownership, which creates problems.
=> file ownership fix

libBuild.sh
Recent refactoring removed the compatible architectures flag, which is used by the CLI and sls plugin for guiding clients to the correct architecture.
=> fix: Restoring compatible architectures

Makefile, libBuild.sh, nodejs/package-lock.json, nodejs/package.json, nodejs/publish-layers.sh
This PR adds Node 16 support, fixes repo links, and updates dependencies (based on npm audit fix)
<sup> Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
=> Add Node 16 support

.circleci/config.yml
Need to add this for Node 16 layers to be built
=> fix: Adding circleCi job for Node 16

.circleci/config.yml
Yet another step before the Node 16 jobs can run.
=> fix: Adding Node 16 build jobs to the CircleCI workflows

java/src/main/java/com/newrelic/java/HandlerWrapper.java
To expose the more details about the issue. The current implementation hides the problem underneath and we need to disable the handler and replace it with the original handler to figure out what is wrong. This change will help a lot to debug issues.
=> Added the original error as a cause

nodejs/index.js
.at() as an array accessor method was added in Node 16, so Node 14 encountered an error.
Closes #101 
=> fix: Handler definition now uses handler index

.circleci/config.yml
NR-55595: Updated circleci config to ensure node images used for node jobs
=> fix: Updated circleci config to ensure node images used for node jobs

README.md
As AWS support for ECMAScript modules in Lambda doesn't extend to Lambda Layers, this documents one possible way of instrumenting.
=> Added documentation for ESM instrumentation in Lambda

libBuild.sh
AWS introduced [new Graviton2-supporting regions](https://aws.amazon.com/about-aws/whats-new/2022/10/aws-lambda-functions-graviton2-12-regions/). This PR adds them to the ARM64 build/publish process. 
Closes NEWRELIC-5557
=> feat: Added new ARM64-supporting regions

.circleci/config.yml, libBuild.sh, python/publish-layers.sh
Python 3.6 is no longer supported by lambda nor the New Relic Python Agent. This PR removes Python 3.6 from the current lambda layers publishing process.
=> Remove build for Python 3.6 layer.

.circleci/config.yml
CircleCI has moved to next-generation images using the `cimg` namespace. As a result, there's no `circleci/node:18 image`. This commit updated all node job images. 
Closes NR-70339
=> Updated CI images for Node jobs

.circleci/config.yml
Aliasing scheme has changed; minor versions required, apparently. 
Closes NR-70339
=> fix: Updated CI images for Node jobs

nodejs/index.js, nodejs/package.json, nodejs/test/fixtures/.hidden/.directory/.handler.js, nodejs/test/fixtures/esm/handler.mjs, nodejs/test/fixtures/handler.js, nodejs/test/layer.tap.js
* add support for esm loading for nodejs18
* switch to async resolve of handler
* add test case to load esm
* extend test case to check that promise contains cached wrapped handler
Implements #126 
I have tested it by creating my own layers and loading it in v18, so fare it worked for me
@mrickard fyi
=> Add support for esm loading

README.md
Notes that no-code-change instrumentation is available for Node 18 with ESM functions. 
Closes NEWRELIC-6493.
=> fix: Updated Node ESM documentation for Node 18

nodejs/index.js, nodejs/package-lock.json, nodejs/package.json, nodejs/test/fixtures/esmPkg/.eslintrc.json, nodejs/test/fixtures/esmPkg/handler.js, nodejs/test/fixtures/esmPkg/package.json
This checks to see if the file was found but attempted require of a module, so we attempt an import instead.
=> fix(NEWRELIC-7409): allow ESM modules to be defined via package.json

.circleci/config.yml
Updating Python `circleci` images to `cimg` in conjunction with [Node image update](https://github.com/newrelic/newrelic-lambda-layers/pull/124).
=> Update Python CI images for Python and Java jobs.

.circleci/config.yml
In #156, we broke the publish job by removing `ciTest` npm script, which internally was calling `npm install` inline to install the dev deps. This updates the circleci job to handle running `npm install` itself
=> fix: update circleci configuration to install deps

.circleci/config.yml
sudo in docker containers is unsafe. The superuser in circle CI does not seem to have pip access.
Example: https://app.circleci.com/pipelines/github/newrelic/newrelic-lambda-layers/631/workflows/49e348cb-3da1-4773-97c6-7af9d174a5c9/jobs/888
```
#!/bin/bash -eo pipefail
sudo pip install -U awscli
sudo: pip: command not found
Exited with code exit status 1
```
=> Update config.yml to remove sudo

.circleci/config.yml
This PR updates the Python 3.10 and 3.11 images from `circleci` to `cimg`.
=> Update Python 3.10 & 3.11 build images.

.circleci/config.yml, Makefile, dockerfiles/Dockerfile.java17, java/.gitignore, java/build.gradle, java/gradle/wrapper/gradle-wrapper.properties, java/publish-layers.sh, libBuild.sh
Thanks to @gliptak for the original PR that added Java 17 support.
- Bumped version of gradle to v7.6.2
- Added `--add-opens` JVM args to gradle `test` lifecycle to get around J17 restrictions on reflecting on core Java classes
- Displays detected Java version during build time
=> Add Java 17 support to the NR lambda layers

.circleci/config.yml, .github/workflows/nodejs.yml, libBuild.sh, nodejs/package-lock.json, nodejs/package.json, nodejs/publish-layers.sh
PR to anticipate Node 20 being introduced as a supported Lambda runtime.
Closes #169 
Closes NR-141663
=> feat: Added Node 20 support

libBuild.sh
Layer publishing CI failed on December 12, with failures pointing to a missing or malformed extension file. See https://app.circleci.com/pipelines/github/newrelic/newrelic-lambda-layers/752/workflows/0d5eb160-1556-4ca8-a14f-efe45b792320/jobs/1017
Node layer tests are unlikely to complete, as they're skipped when there are no Node changes.
=> fix: Revert extension to 2.3.9 to unblock publishing

libBuild.sh
Customers have reported several issues with yesterday's release of the Lambda Extension. This PR reverts to the previously released 2.3.9 while the Extension owners investigate. 
See https://github.com/newrelic/serverless-newrelic-lambda-layers/issues/404 (This issue was reported there because the plugin for Serverless is designed to apply the most recent layer version for a given runtime, so all users of the plugin are blocked from new deployments until a new layer is published.)
=> fix: Revert extension to 2.3.9 

java/build.gradle
The add-opens is not available in Java 8, so preventing the test from using it.
=> fix(java): Guarding Java 11+ feature

java/src/main/java/com/newrelic/java/JavaClassLoader.java
When the following exception was caught, it did not log the stack trace, which made it difficult to figure out what happened.
=> fix(Java): Log exception stack trace

Dockerfile, libBuild.sh
**Ticket**: https://new-relic.atlassian.net/browse/NR-219713
Currently, our Layers scripts is for publish [layers](https://layers.newrelic-external.com/#/get-layers/get) in all regions.
And, we are also created docker lambda [layers in ECRs](https://gallery.ecr.aws/newrelic-lambda-layers-for-docker) for Python, Node and Java. So, We need to publish ECRs if any new versions are released for these languages. 
In this PR :- I've written a bash script code for publishing ECRs automatically if any new releases is happen.  
**How to test**
1. Make sure you are authenticated with AWS test account for testing.
2. I've already created a ECR [repository](https://gallery.ecr.aws/q6k3q1g1?page=1) for testing.
3. Don't forgot to use testing repository for testing purpose.
```
For testing …
```
=> chore: Added bash script and Docker file for auto creation of ECRs for lambda layers

.github/workflows/publish-dotnet.yml, README.md, dotnet/publish-layers.sh, libBuild.sh
Similar to the Python Agent, we don't need to build anything. We can grab the necessary files from the download site to publish.
The same Agent binaries support all the possible .NET Lambda runtimes (.NET 6, 7, and 8), so the only layers that need to be created are x64/ARM64.
Next step will be to add tag creation to our Agent release process.
=> feat: Add initial dotnet Lambda layer support

README.md
This repo's README has directed users to a website that displays the latest ARN of various layers. The site responds to both https://layers.newrelic-external.com/ and https://nr-layers.iopipe.com/. Both URLs are correct, but the latter URL could present some confusion for users. (For context, New Relic acquired IOpipe in 2019, and the corresponding layer discovery site was launched to provide layers helping IOpipe customers onboard to New Relic.) These layers could be used by customers of either to send telemetry to New Relic, and the web content is the same no matter which URL is used, so updating the URL in this document is merely a copyediting change.
=> chore: Updated layer-discovery site URL in README.md

libBuild.sh
Removes the dotnet6 runtime from the NewRelicLambdaExtension by removing it from the "provided" set of runtimes.
With the introduction of the .NET Agent layers, having dotnet6 listed as a runtime on the NewRelicLambdaExtension is breaking tests for the lambda cli and will break scripting for customers.   The CLI will fail and exit if more than one layer exists for a specific runtime and architecture pair when being run from a script and not an interactive terminal.  Looking over the available layers, I am not seeing any other language agent layers that have duplicates.
=> fix: Remove the dotnet6 runtime from the NewRelicLambdaExtension.

libBuild.sh
Created a Docket Hub repository under Newrelic organisation. This Docker image repository contains New Relic Lambda Layer images for Java, Node.js, and Python applications. These images facilitate seamless integration of New Relic's monitoring capabilities into your AWS Lambda functions.
To download the latest Docker image for the Java Lambda layer, use:
_**docker pull newrelic/newrelic-lambda-layers-java:latest**_
To pull a specific version of the Java Lambda layer image, use:
_**docker pull newrelic/newrelic-lambda-layers-java:<version>**_
=> Bashscript update to auto publish layers to docker hub.

.github/workflows/publish-dotnet.yml, dotnet/publish-layers.sh
After talking it over with the team, we've decided to always publish the latest release, rather than trying to use the specific version in the tag.
=> chore: Always use latest release for .NET

.github/workflows/publish-python.yml, python/publish-layers.sh
As per [AWS documentation](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-deprecated), Python 3.7 has been deprecated
Python 3.7 | python3.7 | Amazon Linux | Dec 4, 2023
-- | -- | -- | --
=> remove python3.7 layer

extension/publish-layer.sh, libBuild.sh
Release extension only images in the format [newrelic-lambda-layers-extension] in the public repo for New Relic lambda images: https://gallery.ecr.aws/x6n7b2o2?page=1.
Currently, we have [x6n7b2o2/newrelic-lambda-layers-lambdaextension](https://gallery.ecr.aws/x6n7b2o2/newrelic-lambda-layers-lambdaextension), which was not released with github actions.
=> publish extension only ecr images

libBuild.sh
release layers for extension [v2.3.13](https://github.com/newrelic/newrelic-lambda-extension/releases/tag/v2.3.13)
=> release layers for extension v2.3.13

dotnet/publish-layers.sh
Somehow we missed this in our initial implementation. It's referenced in [our documentation](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/containerized-images/#dotnet) but we have never created one.
=> fix: Create .NET layer for docker

libBuild.sh
- Resolves issue related to publishing of docker ecr images for dotnet. PR [here](https://github.com/newrelic/newrelic-lambda-layers/pull/271)
- Currently we see following error in the [test run](https://github.com/chaudharysaket/newrelic-lambda-layers/actions/runs/10805282963/job/29972132934):
```
docker tag layer-nr-image-dotnet--arm64:latest public.ecr.aws/<test-account>/newrelic-lambda-layers-dotnet:-arm64
Error parsing reference: "public.ecr.aws/<test-account>/newrelic-lambda-layers-dotnet:-arm64" is not a valid repository/tag: invalid reference format
```
- The [publish_docker_ecr code](https://github.com/newrelic/newrelic-lambda-layers/blob/57122f88fc82cbcd7d3480638c16a3cc572ee8ae/libBuild.sh#L265) creates arch_flag with `-` for arm and no arch_flag for `x86_64`. The `:-` is an …
=> Resolve dotnet ecr image format issue

libBuild.sh
- Release New Relic lambda layers with Extension [v2.3.14](https://github.com/newrelic/newrelic-lambda-extension/releases/tag/v2.3.14)
=> release extension v2.3.14

java/build.gradle
Replaces the version of `commons-logging` that is pulled in via the `java-aws-lambda:2.2.0` dependency.
Resolves Issue #283
=> Add Commons-Logging Dependency

.github/workflows/nodejs.yml, .github/workflows/publish-node.yml, dockerfiles/Dockerfile.nodejs22x, libBuild.sh, nodejs/package-lock.json, nodejs/package.json, nodejs/publish-layers.sh
As Node 22 is now available as a [Lambda runtime](https://aws.amazon.com/blogs/compute/node-js-22-runtime-now-available-in-aws-lambda/), we should publish compatible layers. This PR updates the publishing scripts, Dockerfile, and workflows for Node. to include jobs for Node 22.
=> feat: Added publishing for Node 22 layers

libBuild.sh
Update lambda layer release script to use latest Extension [v2.3.15](https://github.com/newrelic/newrelic-lambda-extension/releases/tag/v2.3.15).
=> Update extension version

java/src/main/java/com/newrelic/java/JavaClassLoader.java, java/src/test/java/com/newrelic/java/JavaClassLoaderTest.java, java/src/test/java/com/newrelic/java/PojoHandlerWithNoArgument.java
This PR adds ability to run custom handlers that executes method that doesn't require any arguments. This is fully supported by AWS Lambda environment. The typical example are the scheduled functions where the cron CloudWatch event often doesn't provide any additional value to the function. Once the request goes through this layer, the execution currently fails because the executor expects having either one or two arguments.
=> Support handler methods without any argument

.github/workflows/nodejs.yml, nodejs/package-lock.json, nodejs/package.json
This PR contains newrelic node agent version update to `v12.9.0`
- I have created new layer and tested if we are able to instrument node js lambda function. 
- Create new layer for node js and check if we can see any warning for `node js agent version`
=> chore: bump newrelic node agent from 12.8.0 to 12.9.0

libBuild.sh
Release layers for Extension [v2.3.16](https://github.com/newrelic/newrelic-lambda-extension/releases/tag/v2.3.16)
=> extension v2.3.16 release

.github/workflows/publish-node.yml
- Updating the version which resolves failing while releasing `node.js` layers. 
- Since in actions 5 [code-cov](https://github.com/codecov/codecov-action) has updated the `file` to `files` so updated it as per readme in `code-cov`.
=> Chore: bumps up codecov-action

.github/workflows/python.yml, python/newrelic_lambda_wrapper.py
- As mentioned in the [issue](https://github.com/newrelic/newrelic-lambda-layers/issues/281), the `ImportError` is masking other errors during initializing of module and not providing proper traceback.
- Updated Exception such that other exceptions such as `KeyError` or `ValueError` during import of module get raised properly.
- Remove python 3.7 from CI workflow as it has been deprecated
=> update exception handling

README.md
In ESM, the Node agent uses an experimental loader flag to load some dependencies for instrumentation. This PR adds an instruction for using this loader in Lambda.
=> fix: Added instruction for using the ESM Loader for Node

.github/workflows/publish-ruby.yml, .github/workflows/ruby.yml
- Currently, there is issue with[ Ruby Layer publish workflow](https://github.com/newrelic/newrelic-lambda-layers/actions/runs/13053353305), which is giving following error:
```
Error: The current runner (ubuntu-24.04-x64) was detected as self-hosted because the platform does not match a GitHub-hosted runner image (or that image is deprecated and no longer supported).
```
- Update the workflow config to resolve the compatibility issue.
=> Update Ruby GitHub Actions config for Ubuntu runner

extension/publish-layer.sh, libBuild.sh, nodejs/publish-layers.sh, python/package-lock.json, python/package.json, python/publish-layers.sh
- Add New Relic Language agent version and New Relic Lambda Extension version to Lambda Layer description
- Previous Layer description `New Relic Layer for nodejs18.x (x86_64)`
- Modified Layer description `New Relic Layer for nodejs18.x (x86_64) with New Relic Extension v2.3.17 and Node agent v12.16.1`
- Update serverless packages
=> add agent and extension version to layer description

python/publish-layers.sh
* Fix issue where Python Agent would install the latest available version and release it for a given tag, rather than the exactly correct version.
* This issue has the potential to cause a race condition between the CDN for PyPi and the publishing of layers built here to cause the incorrect Python Agent version to be released.
* This is especially pressing considering the drastically reduced lag between PyPi publish steps and this one, where we've had issues recently on the InitContainer repo with the version not being available yet.
* Deduplicate code for region specific builds in `python/publish_layers.sh`.
* Fix bug in architecture detection where a missing `$` caused all layers to be treated as x86.
* [Example](https://github.com/newrelic/newrelic-lambda-layers/actions/runs/14652430417 …
=> Fix Python Agent Build Determinism

.github/workflows/publish-ruby.yml
- add Ruby 3.4 to release workflow
=> add Ruby 3.4 to release workflow

nodejs/test/integration/serverless.yml
This PR fixes a regression from [this commit](https://github.com/newrelic/newrelic-lambda-layers/commit/3055ce0ff6e48091e9896138333ebacbfd90cf65#diff-afb0d0b832a0ccfb7abdfc81fb479bf3d93946a232148cfffb773c2478a36769L5). It looks like when removing Node 18, we removed the custom runtime so the tests weren't running in any node version.
=> test: fixed integration nodejs tests

nodejs/publish-layers.sh
- To release Node.js 16 layers support
=> chore: update newrelic version to 11.23.2 and add support for Node.js 16
